# Generated by Django 4.2 on 2023-06-07 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_alter_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.IntegerField(null=True)),
                ('date_commande', models.DateField(null=True)),
                ('nom_client', models.CharField(max_length=35, null=True)),
                ('prenom_client', models.CharField(max_length=25, null=True)),
                ('ville', models.CharField(max_length=256, null=True)),
                ('montant_commande', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ugs', models.CharField(max_length=256, null=True)),
                ('id_produit', models.IntegerField(null=True)),
                ('nom_produit', models.CharField(max_length=256, null=True)),
                ('categorie', models.CharField(max_length=500, null=True)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('description_produit', models.CharField(max_length=500)),
                ('id_infopreneur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
