# Generated by Django 4.2 on 2023-06-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Sexe',
            field=models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme'), ('autre', 'Autre')], default='homme', max_length=30, null=True),
        ),
    ]
